from fpdf import FPDF
import tempfile
import os

def clean_text(text):
    """Clean text to be safe for FPDF Helvetica font."""
    if not isinstance(text, str):
        text = str(text)
    # Replace common problematic unicode characters
    text = text.replace('\u2019', "'").replace('\u2018', "'").replace('\u201c', '"').replace('\u201d', '"')
    text = text.replace('\u2013', '-').replace('\u2014', '-')
    # Encode to latin-1 to drop any unsupported characters like emojis or Korean text
    return text.encode('latin-1', 'replace').decode('latin-1')

def generate_pdf_report(df):
    """Generates a professional PDF report from the DataFrame."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # Title
    pdf.set_font("Helvetica", "B", 24)
    pdf.cell(0, 15, "K-Beauty Scout Intelligence Report", ln=True, align="C")
    pdf.set_font("Helvetica", "I", 12)
    pdf.cell(0, 10, "Generated by Glide Strategy Engine", ln=True, align="C")
    pdf.ln(10)
    
    # Summary
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, f"Executive Summary", ln=True)
    pdf.set_font("Helvetica", "", 11)
    summary_text = f"This report evaluates {len(df)} international beauty brands for potential launch in the Indian market. Brands are assessed across global maturity, India market exclusivity, pricing strategy, and formulation viability."
    pdf.multi_cell(0, 8, clean_text(summary_text))
    pdf.ln(5)
    
    for index, row in df.iterrows():
        pdf.add_page()
        
        # Brand Header
        pdf.set_font("Helvetica", "B", 18)
        pdf.set_text_color(220, 20, 60) # Crimson
        pdf.cell(0, 10, clean_text(row['Brand Name']), ln=True)
        pdf.set_text_color(0, 0, 0)
        
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, clean_text(f"Glide Launch Suitability Score: {row.get('Suitability Score', 0)}/100"), ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, clean_text(f"Price Positioning: {row.get('Price Positioning', 'Unknown')}  |  Demographic: {row.get('Target Demographic', 'Unknown')}"), ln=True)
        pdf.ln(5)
        
        # Advanced Analytics Sub-Scores
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Core Metrics (0-10)", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(45, 6, clean_text(f"Global Maturity: {row.get('Global Maturity Score', 0)}"))
        pdf.cell(45, 6, clean_text(f"India Exclusivity: {row.get('India Exclusivity Score', 0)}"))
        pdf.cell(45, 6, clean_text(f"Brand Buzz: {row.get('Brand Buzz Score', 0)}"))
        pdf.cell(45, 6, clean_text(f"Formulation: {row.get('Formulation Complexity Score', 0)}"))
        pdf.ln(10)
        
        # Strategy
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Market Strategy", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, clean_text(f"Hero Product: {row.get('Hero Product', 'N/A')}"))
        pdf.multi_cell(0, 6, clean_text(f"Market Gap Fit: {row.get('Market Gap Fit', 'N/A')}"))
        pdf.multi_cell(0, 6, clean_text(f"Pricing Strategy: {row.get('Pricing Strategy', 'N/A')}"))
        pdf.ln(5)
        
        # Detailed Logic
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Detailed Strategic Rationale", ln=True)
        pdf.set_font("Helvetica", "", 10)
        logic = row.get('Detailed Logic', row.get('Rationale', 'N/A'))
        pdf.multi_cell(0, 6, clean_text(logic))
        pdf.ln(5)
        
        # Pros and Cons
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Pros & Cons", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pros = row.get('Pros', [])
        cons = row.get('Cons', [])
        
        if pros and isinstance(pros, list):
            pdf.cell(0, 6, "Strengths:", ln=True)
            for p in pros:
                pdf.multi_cell(0, 6, clean_text(f"  + {p}"))
        if cons and isinstance(cons, list):
            pdf.cell(0, 6, "Weaknesses/Risks:", ln=True)
            for c in cons:
                pdf.multi_cell(0, 6, clean_text(f"  - {c}"))
        pdf.ln(5)
        
        # Key Ingredients
        ingreds = row.get('Key Ingredients', [])
        if ingreds and isinstance(ingreds, list):
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(0, 8, "Key Ingredients", ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 6, clean_text(", ".join(ingreds)))
    
    # Save to a temporary file and return the bytes
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        pdf.output(tmp.name)
        with open(tmp.name, "rb") as f:
            pdf_bytes = f.read()
    
    os.remove(tmp.name)
    return pdf_bytes
