from fpdf import FPDF
import tempfile
import os

def generate_pdf_report(df):
    """Generates a professional PDF report from the DataFrame."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # Title
    pdf.set_font("Helvetica", "B", 24)
    pdf.cell(0, 15, "K-Beauty Scout Intelligence Report", ln=True, align="C")
    pdf.set_font("Helvetica", "I", 12)
    pdf.cell(0, 10, "Generated by Glide Strategy Engine", ln=True, align="C")
    pdf.ln(10)
    
    # Summary
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, f"Executive Summary", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 8, f"This report evaluates {len(df)} international beauty brands for potential launch in the Indian market. Brands are assessed across global maturity, India market exclusivity, pricing strategy, and formulation viability.")
    pdf.ln(5)
    
    for index, row in df.iterrows():
        pdf.add_page()
        
        # Brand Header
        pdf.set_font("Helvetica", "B", 18)
        pdf.set_text_color(220, 20, 60) # Crimson
        pdf.cell(0, 10, f"{row['Brand Name']}", ln=True)
        pdf.set_text_color(0, 0, 0)
        
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, f"Glide Launch Suitability Score: {row['Suitability Score']}/100", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, f"Price Positioning: {row['Price Positioning']}  |  Demographic: {row.get('Target Demographic', 'Unknown')}", ln=True)
        pdf.ln(5)
        
        # Advanced Analytics Sub-Scores
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Core Metrics (0-10)", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(45, 6, f"Global Maturity: {row['Global Maturity Score']}")
        pdf.cell(45, 6, f"India Exclusivity: {row['India Exclusivity Score']}")
        pdf.cell(45, 6, f"Brand Buzz: {row.get('Brand Buzz Score', 0)}")
        pdf.cell(45, 6, f"Formulation: {row.get('Formulation Complexity Score', 0)}")
        pdf.ln(10)
        
        # Strategy
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Market Strategy", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, f"Hero Product: {row.get('Hero Product', 'N/A')}")
        pdf.multi_cell(0, 6, f"Market Gap Fit: {row.get('Market Gap Fit', 'N/A')}")
        pdf.multi_cell(0, 6, f"Pricing Strategy: {row.get('Pricing Strategy', 'N/A')}")
        pdf.ln(5)
        
        # Detailed Logic
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Detailed Strategic Rationale", ln=True)
        pdf.set_font("Helvetica", "", 10)
        logic = row.get('Detailed Logic', row.get('Rationale', 'N/A'))
        # Fix encoding issues by replacing unsupported chars
        logic = logic.encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 6, logic)
        pdf.ln(5)
        
        # Pros and Cons
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Pros & Cons", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pros = row.get('Pros', [])
        cons = row.get('Cons', [])
        
        if pros:
            pdf.cell(0, 6, "Strengths:", ln=True)
            for p in pros:
                pdf.multi_cell(0, 6, f"  + {p.encode('latin-1', 'replace').decode('latin-1')}")
        if cons:
            pdf.cell(0, 6, "Weaknesses/Risks:", ln=True)
            for c in cons:
                pdf.multi_cell(0, 6, f"  - {c.encode('latin-1', 'replace').decode('latin-1')}")
        pdf.ln(5)
        
        # Key Ingredients
        ingreds = row.get('Key Ingredients', [])
        if ingreds:
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(0, 8, "Key Ingredients", ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 6, ", ".join(ingreds).encode('latin-1', 'replace').decode('latin-1'))
    
    # Save to a temporary file and return the bytes
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        pdf.output(tmp.name)
        with open(tmp.name, "rb") as f:
            pdf_bytes = f.read()
    
    os.remove(tmp.name)
    return pdf_bytes
